### ISSUE TITLE
agentless vehicle can not be created

### ISSUE THREAD

**Issue by drac** [cad/vehicle-tracker-api#19]
When you try to create a vehicle without `agent_uuid`, in a system that has **no agents** in database (agents are never been created);

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer 23cc0605-a2fc-4cfc-a403-233054625d0c' -d '{ \ 
   "plate_id": "AA111", \ 
   "type": "SCHOOL-BUS" \ 
 }' 'http://localhost:5004/vehicle/'
```

```
{
  "updated_at": "2017-09-12T14:49:22.938391664+03:00",
  "plate_id": "AA111",
  "agent": {
    "uuid": "",
    "updated_at": "0001-01-01T00:00:00Z",
    "label": "",
    "lat": "",
    "lon": "",
    "gps_ts": ""
  },
  "groups": null,
  "type": "SCHOOL-BUS"
}
```

you are able to create a vehicle without an agent assigned to it, an agentless vehicle.

**But** what you can not do is; when you try to create a vehicle without `agent_uuid`, in a system that has **at least one agent**, you ending up with a vehicle that an agent assigned to it.

For testing, lets create an agent for the first time and call it `firstagent`;

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer 23cc0605-a2fc-4cfc-a403-233054625d0c' -d '{ \ 
   "lat": "1111", \ 
   "lon": "1111", \ 
   "ts": "1111" \ 
 }' 'http://localhost:5004/agent/firstagent/sync'
```

And now when we try to create a vehicle without an agent;

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer 23cc0605-a2fc-4cfc-a403-233054625d0c' -d '{ \ 
   "plate_id": "BB222", \ 
   "type": "SCHOOL-BUS" \ 
 }' 'http://localhost:5004/vehicle/'
```

```
{
  "updated_at": "2017-09-12T14:59:22.943486352+03:00",
  "plate_id": "BB222",
  "agent": {
    "uuid": "firstagent",
    "updated_at": "2017-09-12T14:59:22.941804212+03:00",
    "label": "",
    "lat": "1111",
    "lon": "1111",
    "gps_ts": "1111"
  },
  "groups": null,
  "type": "SCHOOL-BUS"
}
```

it created with the first agent already assigned to it.

**PS.:** It doesn't matter how many agents you have in the system, you always ending up assigned to the first agent ever created.

**Comment by cad** [comment]
@drac Thanks for reporting this bug. 🙏  Seems like a stupid one. :joy:

This issue should be fixed now.  Please try and if it occurs again, please reopen.
